apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: '{{ .Release.Namespace }}'
type: Opaque
data:
  jupyterToken: '{{ include "chart.secret.jupyterToken" . | b64enc }}'
  postgresUsername: '{{ .Values.api.secrets.postgresUsername | b64enc }}'
  postgresPassword: '{{ .Values.api.secrets.postgresPassword | b64enc }}'
  loginJwtSecret: '{{ include "chart.secret.loginJwtSecret" . | b64enc }}'
  authJwtSecret: '{{ include "chart.secret.authJwtSecret" . | b64enc }}'
  aiApiUsername: '{{ .Values.ai.secrets.aiApiUsername | default "" | b64enc }}'
  aiApiPassword: '{{ .Values.ai.secrets.aiApiPassword | default "" | b64enc }}'
  datasourcesEncryptionKey: '{{ include "chart.secret.datasourcesEncryptionKey" . | b64enc }}'
  environmentVariablesEncryptionKey: '{{ include "chart.secret.environmentVariablesEncryptionKey" . | b64enc }}'
  integrationsConfigEncryptionKey: '{{ include "chart.secret.integrationsConfigEncryptionKey" . | b64enc }}'
  workspaceSecretsEncryptionKey: '{{ include "chart.secret.workspaceSecretsEncryptionKey" . | b64enc }}'
